# Generated by Django 2.2.28 on 2022-10-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsch', '0004_alter_lessondate_id_alter_status_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
